version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nada_docker
    ports:
      - "127.0.0.1:8383:80"
    volumes:
      - ./nada:/var/www/html/nada
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: nada_docker
      DB_USERNAME: nada_user
      DB_PASSWORD: nada_password      
  mysql:
      image: mysql:5.7
      container_name: mysql-57
      restart: always
      ports:
        - 13306:3306
      environment:
        MYSQL_DATABASE: nada_docker
        MYSQL_USER: nada_user
        MYSQL_PASSWORD: nada_password
        MYSQL_ROOT_PASSWORD: root